;;; Copyright © 2025 Nikita Mitasov <mitanick@ya.ru>
;; DO NOT EDIT! AUTOGENERATED WITH bin/config
;; In future I would edit config.scm to use values from here

(define-module (modules channels)
  #:use-module (guix)
  #:use-module (guix channels)
  #:use-module (srfi srfi-1))

(define-public my-channels
  (list
(channel
  (name 'guix)
  (url "https://codeberg.org/guix/guix.git")
  (commit
    "b1438011b38199b674c6f3aea7ffd37a2886749e")
  (introduction
    (make-channel-introduction
      "9edb3f66fd807b096b48283debdcddccfea34bad"
      (openpgp-fingerprint
        "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
(channel
  (name 'nonguix)
  (url "https://gitlab.com/nonguix/nonguix.git")
  (commit
    "b8c13cd2c8e3fec32facdf64c57e74e1461398a7")
  (introduction
    (make-channel-introduction
      "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
      (openpgp-fingerprint
        "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5"))))
(channel
  (name 'pognul)
  (url "https://codeberg.org/ch4og/pognul-guix-channel.git")
  (branch "main")
  (commit
    "f2c8cca45782fa2b06f39e54082759f8c7730430")
  (introduction
    (make-channel-introduction
      "c57a1c7744e08331538121238e3f5fc109271796"
      (openpgp-fingerprint
        "7C9E 7EBA 828C 58DF DACE  5BED 4DCC 7AB7 FC75 319B"))))
))

my-channels
