;; DO NOT EDIT! AUTOGENERATED WITH bin/config
;; In future I would edit config.scm to use values from here
(list (channel
        (name 'guix)
        (url "https://codeberg.org/guix/guix.git")
        (commit
          "8ee456e2bda8f72ccaf2398a1709a85e6e32d952")
        (introduction
          (make-channel-introduction
            "9edb3f66fd807b096b48283debdcddccfea34bad"
            (openpgp-fingerprint
              "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
      (channel
        (name 'nonguix)
        (url "https://gitlab.com/nonguix/nonguix.git")
        (commit
          "c16a92e3bef67a602bc56b0dd20ecdc8cac8c97f")
        (introduction
          (make-channel-introduction
            "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
            (openpgp-fingerprint
              "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5"))))
      (channel
        (name 'pognul)
        (url "https://codeberg.org/ch4og/pognul-guix-channel.git")
        (branch "main")
        (commit
          "537abcb57df8977d97066876dd442a879a9227fd")))
