(use-modules (guix channels)
             (gnu services)
             (ice-9 match)
             (ice-9 popen)
             (ice-9 rdelim)
             (ice-9 pretty-print))

(define (get-last-commit repo)
  (let ((p (open-pipe* OPEN_READ "git" "ls-remote" repo "HEAD")))
    (let ((out (read-line p)))
      (close-pipe p)
      (car (string-split out #\tab)))))

(define (channels)
  (list
   (channel
    (name 'guix)
    (url "https://codeberg.org/guix/guix.git")
    (introduction
     (make-channel-introduction
      "9edb3f66fd807b096b48283debdcddccfea34bad"
      (openpgp-fingerprint "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))
    (commit (get-last-commit "https://codeberg.org/guix/guix.git")))

   (channel
    (name 'nonguix)
    (url "https://gitlab.com/nonguix/nonguix.git")
    (introduction
     (make-channel-introduction
      "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
      (openpgp-fingerprint "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5")))
    (commit (get-last-commit "https://gitlab.com/nonguix/nonguix.git")))))


(with-output-to-file "channels.scm"
  (lambda ()
    (display ";; DO NOT EDIT! AUTOGENERATED WITH update.scm")
    (newline)
    (display ";; In future I would edit update.scm to use values from here")
    (newline)
    (pretty-print `(list ,@(map channel->code (channels))))))
