(use-modules
 (guix utils)
 (gnu packages)
 (gnu packages wm)
 (nongnu packages nvidia)
 (guix transformations))
(define transform
  (options->transformation
   '((with-graft . "mesa=nvda"))))
(map transform
     (map specification->package
	  '("bat"
	    "blueman"
	    "btop"
	    "curl"
	    "emacs"
	    "eog"
	    "eza"
	    "fastfetch"
	    "fd"
	    "file"
	    "file-roller"
	    "filezilla"
	    "firefox"
	    "font-awesome-nonfree"
	    "font-google-noto"
	    "fontforge"
	    "fzf"
	    "grim"
	    "heroic-nvidia"
	    "hyprland"
	    "hyprpaper"
	    "kdenlive"
	    "kitty"
	    "krita"
	    "lazygit"
	    "libreoffice"
	    "mpv"
	    "ncurses"
	    "neovim"
	    "nftables"
	    "oils"
	    "pavucontrol"
	    "pcmanfm"
	    "pipewire"
	    "qbittorrent-enhanced"
	    "quickshell"
	    "remmina"
	    "ripgrep"
	    "rofi-wayland"
	    "starship"
	    "telegram-desktop"
	    "torbrowser"
	    "unzip"
	    "virt-manager"
	    "waybar"
	    "wireplumber"
	    "wireplumber"
	    "wl-clipboard"
	    "wtype"
	    "xdg-desktop-portal"
	    "xdg-desktop-portal-hyprland"
	    "xdg-utils"
	    "zip"
	    "zoom"
	    "zoxide"
	    "zsh"
	    "zsh-syntax-highlighting")))
